//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Scripts.UI.View
{
    
    public enum Player_View_Panel
    {
    }
    public enum Player_View_Widget
    {
        SetSpeed_Button,
        LoadLevel_Button,
        LoadAvatar_Button,
        Speed_InputField,
    }
}
