//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Scripts.UI.View
{
    using Base;
    using System;
    using UnityEngine;
    
    public partial class Player_View : ViewBase
    {
        // member
        public UnityEngine.UI.Button SetSpeed_Button;
        public UnityEngine.UI.Button LoadLevel_Button;
        public UnityEngine.UI.Button LoadAvatar_Button;
        public UnityEngine.UI.InputField Speed_InputField;
        public Framework.Scripts.UI.View.Player_View_ScriptableObject Player_View_ScriptableObject;
        // member end
        internal override object GetWidget(string widgetName)
        {
            if (!Enum.TryParse(widgetName, true, out Player_View_Widget _))
            {
                // Debug.LogError(gameObject.name + " has not widget : " + widgetName);
                return null;
            }
            else
            {
                return base.GetWidget(widgetName);
            }
        }
    }
}
