//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Scripts.UI.View
{
    using Base;
    using UniRx;    
    using System;
    using UnityEngine;
    using Framework.Scripts.Manager;
    
    public sealed partial class BiaoTi_View : ViewBase
    {
        private void Start()
        {
            EnterGame_Button.AddButtonClickEvent(EnterGame).Subscribe((unit =>
            {
                
                
            }));
        }

        public void EnterGame()
        {
            ChangePanel<Player_View>();
        }
        
    }
}
