//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Scripts.UI.View
{
    
    public enum AllViewEnum
    {
        Main_View,
        Test2_View,
        Test_View,
        BiaoTi_View,
        Player_View,
        MaxValue,
    }
}
