//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Scripts.UI.View
{
    
    public enum Main_View_Panel
    {
        Top_Panel,
        Center_Panel,
        Bottom_Panel,
        Bottom2_Panel,
    }
    public enum Main_View_Widget
    {
        Main_View,
        LeftTop_Text,
        CenterTop_Text,
        RightTop_Text,
        Center_Text,
        CenterRight_Text,
    }
}
