//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine.UI;

namespace Framework.Scripts.UI.View
{
    using Base;
    
    public class Main_View : ViewBase
    {
        public Text LeftTop_Text;
        public Text CenterTop_Text;

        public void Test() {}
    }
}
