//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Scripts.UI.View
{
    
    public enum Main_View_Panel
    {
    }
    public enum Main_View_Widget
    {
        BG_Image,
        Top_CustomPanel,
        LeftTop_Text,
        CenterTop_Text,
        RightTop_Text,
        Setting_Button,
        Center_CustomPanel,
        Center_Text,
        CenterRight_Text,
        Bottom_CustomPanel,
        SelectFont_CustomPanel,
        Text_Dropdown,
        Font_Dropdown,
        ChangeFont_Button,
    }
}
