//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.Scripts.Manager;

namespace Framework.Scripts.UI.View
{
    using Base;
    using System;
    using UnityEngine;
    using Base.RedDot;
    using Constants;
    
    public class Test_View : ViewBase
    {
        // member
		public UnityEngine.UI.Button Test_Button;
		public UnityEngine.UI.Button Test3_Button;
        public RedDotBase RedDot;
        public RedDotBase RedDot2;
        // member end
        internal override object GetWidget(string widgetName)
        {
            if (!Enum.TryParse(widgetName, true, out Test_View_Widget _))
            {
                // Debug.LogError(gameObject.name + " has not widget : " + widgetName);
                return null;
            }
            else
            {
                return base.GetWidget(widgetName);
            }
        }

        private void Update()
        {
            if (Input.GetKeyDown(KeyCode.A))
            {
                EventManager.Instance.DispatchEvent(EventConstants.RedDot);
            }

            if (Input.GetKeyDown(KeyCode.B))
            {
                EventManager.Instance.DispatchEvent(EventConstants.StartGame);
            }
        }

        private void Start()
        {
            // LevelManager.Instance.levelType = LevelType.yanjiang;
            // await LevelManager.Instance.LoadLevel(transform);
            RedDot.AddRedDotEventListener(EventConstants.RedDot);
            RedDot2.AddRedDotEventListener(EventConstants.StartGame);
        }
    }
}
